### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by Eseperio** [bupy7/yii2-activerecord-history#5]
https://github.com/bupy7/yii2-activerecord-history/blob/90c29e0c8747e4701674271ebefe3c3eff34c305/behaviors/History.php#L203

Why is calling `$this->getPrimaryKey()` and then getting owner property?

**Comment by bupy7** [comment]
@Eseperio Primary key may be not only `id` as well as `some)id`, `myCustomId` and etc.
